# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Samy Duc
tagline:          'French, GameDev and hacker. Full time dreamer'
description:      'Follow <a href="https://twitter.com/ricklesauceur" target="_blank">@ricklesauceur</a>.'
url:             

baseurl:          / 

author:
  name:           'Samy Duc'
  url:            https://twitter.com/ricklesauceur

paginate:         1

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/ricklesauceur
  
  
gems:
  - jekyll-sitemap
